[package]
name = "radius-log-webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.7"
winreg = "0.50"
quick-xml = { version = "0.31", features = ["serialize"] }
serde_json = "1.0.149"
actix-web-actors = "4.0"
notify = "6.1"
tokio = { version = "1", features = ["full"] }
csv = "1.3"
rand = "0.10.0"
actix = "0.13.5"
windows = { version = "0.52", features = ["Win32_System_EventLog", "Win32_Foundation", "Win32_Security_Cryptography", "Win32_System_Registry"] }
