[files]
extend-exclude = [
    "*.min.js",
    "target/",
    "Cargo.lock",
    "locales/fr.json"
]

[default.extend-words]
# Termes techniques ou abréviations légitimes
EDE = "EDE"
ue = "ue"
ot = "ot"
Ot = "Ot"
Ue = "Ue"
PERSISTANCE = "PERSISTANCE"
EFFET = "EFFET"
CALCULS = "CALCULS"
Attributs = "Attributs"
